title: Adam
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer. Reno, Nevada.  
  <br><br>
  Interested in deep learning, functional programming and data science. 
  <br><br>
  <a href="https://www.linkedin.com/in/adam-montano-74759117a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
page-col: "#123123"
