title: Adam
logo: "/images/adamlogogray.png?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer. Las Vegas, Nevada.  
  <br><br>
  Interested in software engineering, functional programming and free + open source software. Email me for a resume!  
  <br><br>
  <a href="mailto: adam.m.montano@gmail.com">Email Me</a>
  <br><br>
  <a href="https://www.linkedin.com/in/adam-m-74759117a/">View My LinkedIn Profile</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
page-col: "#123123"
